# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-07 12:32
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('competitions', '0002_submission'),
    ]

    operations = [
        migrations.CreateModel(
            name='Organizer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('institution', models.CharField(max_length=50)),
                ('avatar', models.FileField(null=True, upload_to='uploads/avatars/')),
                ('email', models.EmailField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Subtrack',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('training_data', models.FileField(null=True, upload_to='databases/')),
            ],
        ),
        migrations.CreateModel(
            name='Track',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('competition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='competitions.Competition')),
            ],
        ),
        migrations.RenameField(
            model_name='participant',
            old_name='name',
            new_name='groupname',
        ),
        migrations.RenameField(
            model_name='submission',
            old_name='name',
            new_name='method_info',
        ),
        migrations.AddField(
            model_name='participant',
            name='avatar',
            field=models.FileField(null=True, upload_to='uploads/avatars/'),
        ),
        migrations.AddField(
            model_name='participant',
            name='date_joined',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='participant',
            name='date_lastsubmitted',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='submission',
            name='participant',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='competitions.Participant'),
        ),
        migrations.AddField(
            model_name='submission',
            name='resultfile',
            field=models.FileField(null=True, upload_to='uploads/submitted_results/'),
        ),
        migrations.AddField(
            model_name='submission',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='subtrack',
            name='track',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='competitions.Track'),
        ),
        migrations.AddField(
            model_name='competition',
            name='organizer',
            field=models.ManyToManyField(to='competitions.Organizer'),
        ),
        migrations.AddField(
            model_name='submission',
            name='subtrack',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='competitions.Subtrack'),
        ),
    ]
