# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-07 12:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competitions', '0003_auto_20160607_1532'),
    ]

    operations = [
        migrations.AddField(
            model_name='submission',
            name='publishable',
            field=models.BooleanField(default=True),
        ),
    ]
