# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-08 12:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competitions', '0005_benchmark'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subtrack',
            old_name='training_data',
            new_name='public_data',
        ),
        migrations.AddField(
            model_name='subtrack',
            name='private_data',
            field=models.FileField(null=True, upload_to='databases/'),
        ),
        migrations.RemoveField(
            model_name='submission',
            name='participant',
        ),
        migrations.AddField(
            model_name='submission',
            name='participant',
            field=models.ManyToManyField(to='competitions.Participant'),
        ),
    ]
