# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-21 16:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competitions', '0006_auto_20160608_1506'),
    ]

    operations = [
        migrations.AddField(
            model_name='competition',
            name='overview',
            field=models.TextField(default=''),
        ),
    ]
