# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-21 16:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competitions', '0007_competition_overview'),
    ]

    operations = [
        migrations.AddField(
            model_name='competition',
            name='important_dates',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='competition',
            name='newsfeed',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='organizer',
            name='shortbio',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='participant',
            name='groupinfo',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='track',
            name='overview',
            field=models.TextField(default=''),
        ),
    ]
