# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-23 11:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competitions', '0010_auto_20160623_1407'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='affiliation',
            name='members',
        ),
        migrations.AddField(
            model_name='individual',
            name='affiliations',
            field=models.ManyToManyField(to='competitions.Affiliation'),
        ),
    ]
