# -*- coding: utf-8 -*-
# Generated by Django 1.10.dev20160115151452 on 2016-06-26 18:02
from __future__ import unicode_literals

import competitions.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competitions', '0012_auto_20160625_1849'),
    ]

    operations = [
        migrations.RenameField(
            model_name='submission',
            old_name='slug',
            new_name='name',
        ),
        migrations.AlterField(
            model_name='submission',
            name='resultfile',
            field=models.FileField(null=True, upload_to=competitions.models.submission_path),
        ),
    ]
