# -*- coding: utf-8 -*-
# Generated by Django 1.10.dev20160115151452 on 2016-06-26 19:12
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('competitions', '0013_auto_20160626_2102'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubmissionStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numericalresult', models.CharField(default='', max_length=100)),
                ('status', models.CharField(choices=[('UNDEFINED', 'The processing state of the submission is undefined'), ('ERROR', 'An error has occured before processing could start'), ('PROCESSING', 'We are currently processing the submitted result'), ('ERROR_PROCESSING', 'An error has occured during processing of the submitted result'), ('COMPLETE', 'The submitted result has been succesfully processed and a numerical result has been saved')], max_length=20)),
            ],
        ),
        migrations.AddField(
            model_name='benchmark',
            name='benchmark_info',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='benchmark',
            name='subtracks',
            field=models.ManyToManyField(to='competitions.Subtrack'),
        ),
        migrations.AlterField(
            model_name='benchmark',
            name='name',
            field=models.SlugField(default=''),
        ),
        migrations.AddField(
            model_name='submissionstatus',
            name='benchmark',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='competitions.Benchmark'),
        ),
        migrations.AddField(
            model_name='submissionstatus',
            name='submission',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='competitions.Submission'),
        ),
    ]
