# -*- coding: utf-8 -*-
# Generated by Django 1.10.dev20160115151452 on 2016-06-26 20:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competitions', '0014_auto_20160626_2212'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submissionstatus',
            name='status',
            field=models.CharField(choices=[('UNDEFINED', 'The processing state of the submission is undefined'), ('ERROR', 'An error has occured before processing could start'), ('PROCESSING', 'We are currently processing the submitted result'), ('ERROR_PROCESSING', 'An error has occured during processing of the submitted result'), ('COMPLETE', 'The submitted result has been succesfully processed and a numerical result has been saved')], default='UNDEFINED', max_length=20),
        ),
    ]
