# -*- coding: utf-8 -*-
# Generated by Django 1.10.dev20160115151452 on 2016-06-28 13:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competitions', '0015_auto_20160626_2305'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='submissionstatus',
            options={'verbose_name_plural': 'submission status'},
        ),
        migrations.AddField(
            model_name='submissionstatus',
            name='end_time',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='submissionstatus',
            name='start_time',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='subtrack',
            name='public_data_external',
            field=models.URLField(blank=True, default='', null=True),
        ),
    ]
