# -*- coding: utf-8 -*-
# Generated by Django 1.10.dev20160115151452 on 2016-06-28 13:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competitions', '0016_auto_20160628_1635'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subtrack',
            name='public_data',
            field=models.FileField(blank=True, default='', null=True, upload_to='databases/'),
        ),
    ]
