# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-30 10:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competitions', '0017_auto_20160628_1637'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submissionstatus',
            name='status',
            field=models.CharField(choices=[('UNDEFINED', 'The processing state of the submission is undefined'), ('PROCESSING', 'We are currently processing the submitted result'), ('ERROR_EVALUATOR', 'Could not call the related evaluator function'), ('ERROR_GENERIC', 'An error has occured before processing could start'), ('ERROR_PROCESSING', 'An error has occured during processing of the submitted result'), ('COMPLETE', 'The submitted result has been succesfully processed and a numerical result has been saved')], default='UNDEFINED', max_length=20),
        ),
    ]
