# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-01 09:55
from __future__ import unicode_literals

import competitions.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competitions', '0018_auto_20160630_1009'),
    ]

    operations = [
        migrations.AddField(
            model_name='subtrack',
            name='private_data_securehash',
            field=models.CharField(blank=True, default='', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='subtrack',
            name='private_data',
            field=models.FileField(null=True, upload_to=competitions.models.privatedata_path),
        ),
        migrations.AlterField(
            model_name='subtrack',
            name='public_data',
            field=models.FileField(blank=True, default='', null=True, upload_to=competitions.models.publicdata_path),
        ),
    ]
