# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-01 14:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competitions', '0019_auto_20160701_1255'),
    ]

    operations = [
        migrations.AddField(
            model_name='track',
            name='percomp_uniqueid',
            field=models.IntegerField(default='1'),
        ),
    ]
