# -*- coding: utf-8 -*-
# Generated by Django 1.10.dev20160115151452 on 2016-07-08 21:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competitions', '0023_remove_benchmark_evaluator_function_argumentordinal'),
    ]

    operations = [
        migrations.AddField(
            model_name='benchmark',
            name='countinscoreboard',
            field=models.ManyToManyField(to='competitions.Competition'),
        ),
        migrations.AlterField(
            model_name='submissionstatus',
            name='status',
            field=models.CharField(choices=[('UNDEFINED', 'The processing state of the submission is undefined'), ('PROCESSING', 'We are currently processing the submitted result'), ('ERROR_EVALUATOR', 'Could not call the related evaluator function'), ('ERROR_GENERIC', 'An error has occured before processing could start'), ('ERROR_PROCESSING', 'An error has occured during processing of the submitted result'), ('ERROR_UNSUPPORTED', 'This benchmark cannot be computed by the specified evaluator function'), ('COMPLETE', 'The submitted result has been succesfully processed and a numerical result has been saved')], default='UNDEFINED', max_length=20),
        ),
    ]
