# -*- coding: utf-8 -*-
# Generated by Django 1.10.dev20160115151452 on 2016-07-08 21:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competitions', '0024_auto_20160709_0024'),
    ]

    operations = [
        migrations.AlterField(
            model_name='benchmark',
            name='countinscoreboard',
            field=models.ManyToManyField(blank=True, to='competitions.Competition'),
        ),
    ]
