# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-10-12 13:23
from __future__ import unicode_literals

import competitions.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('competitions', '0030_auto_20160909_1333'),
    ]

    operations = [
        migrations.CreateModel(
            name='PublicLinks',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('legend', models.CharField(default='Download training data', max_length=150)),
                ('downloadableFile', models.FileField(blank=True, default='', null=True, upload_to=competitions.models.publicdata_path)),
                ('externalLink', models.URLField(blank=True, default='', null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='subtrack',
            name='public_data',
        ),
        migrations.RemoveField(
            model_name='subtrack',
            name='public_data_external',
        ),
        migrations.AddField(
            model_name='publiclinks',
            name='subtrack',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='competitions.Subtrack'),
        ),
    ]
