# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-11-08 08:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competitions', '0033_benchmark_higher_is_better'),
    ]

    operations = [
        migrations.AddField(
            model_name='competition',
            name='is_public',
            field=models.BooleanField(default=True),
        ),
    ]
