# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-02-13 14:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competitions', '0034_competition_is_public'),
    ]

    operations = [
        migrations.AddField(
            model_name='competition',
            name='leading_organizer',
            field=models.ManyToManyField(related_name='leading_organizer', to='competitions.Individual'),
        ),
        migrations.AddField(
            model_name='competition',
            name='midtier_organizer',
            field=models.ManyToManyField(related_name='midtier_organizer', to='competitions.Individual'),
        ),
    ]
