# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-02-13 15:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competitions', '0035_auto_20170213_1608'),
    ]

    operations = [
        migrations.AlterField(
            model_name='competition',
            name='leading_organizer',
            field=models.ManyToManyField(blank=True, related_name='leading_organizer', to='competitions.Individual'),
        ),
        migrations.AlterField(
            model_name='competition',
            name='midtier_organizer',
            field=models.ManyToManyField(blank=True, related_name='midtier_organizer', to='competitions.Individual'),
        ),
        migrations.AlterField(
            model_name='individual',
            name='shortbio',
            field=models.TextField(blank=True, default=''),
        ),
    ]
