# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-02-14 16:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competitions', '0036_auto_20170213_1728'),
    ]

    operations = [
        migrations.AddField(
            model_name='competition',
            name='submission_is_open',
            field=models.BooleanField(default=True),
        ),
    ]
