# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-02-16 11:24
from __future__ import unicode_literals

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('competitions', '0037_competition_submission_is_open'),
    ]

    operations = [
        migrations.AddField(
            model_name='individual',
            name='activation_token',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
    ]
