# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-03-17 11:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competitions', '0039_competition_url_alias'),
    ]

    operations = [
        migrations.AddField(
            model_name='competition',
            name='force_private_submissions',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='competition',
            name='force_undeletable_submissions',
            field=models.BooleanField(default=True),
        ),
    ]
