# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-04-11 13:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competitions', '0040_auto_20170317_1324'),
    ]

    operations = [
        migrations.AddField(
            model_name='competition',
            name='watchers',
            field=models.ManyToManyField(blank=True, related_name='watchers', to='competitions.Individual'),
        ),
    ]
