# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-06-06 13:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competitions', '0041_competition_watchers'),
    ]

    operations = [
        migrations.AddField(
            model_name='competition',
            name='submission_restriction_in_minutes',
            field=models.IntegerField(default='20'),
        ),
    ]
