# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-06-06 14:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competitions', '0042_competition_submission_restriction_in_minutes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='competition',
            name='submission_restriction_in_minutes',
            field=models.IntegerField(default='20', verbose_name='Time restriction (in minutes) between consecutive submissions (may be set to zero)'),
        ),
    ]
