# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-04-16 08:48
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('competitions', '0043_auto_20170606_1711'),
    ]

    operations = [
        migrations.AddField(
            model_name='competition',
            name='cc_email',
            field=models.EmailField(blank=True, max_length=254, verbose_name='An email will be sent here, everytime there is a submission'),
        ),
        migrations.AddField(
            model_name='competition',
            name='deadline',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='competition',
            name='deadline_active',
            field=models.BooleanField(default=False),
        ),
    ]
